# Generated by Django 4.0.3 on 2022-04-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
                ('rua', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('num', models.CharField(max_length=10)),
                ('compl', models.CharField(max_length=20)),
            ],
        ),
    ]
